### ISSUE TITLE
Deleting item in basket can leave customer confused

### ISSUE THREAD

**Issue by triszt4n** [kir-dev/kbpr-web#41]
### Steps to reproduce:

1. Hozzáadok egy terméket
![image](https://github.com/kir-dev/kbpr-web/assets/60111772/64987708-be84-4159-8a33-59c698bdd5e9)
2. Megnyomom a Törlés gombot --> Content missing --> Mégis a fizetendő bennmarad
![image](https://github.com/kir-dev/kbpr-web/assets/60111772/0d4fbbbe-f4ca-4727-907a-ae9509bc6a72)
3. Ha újranyomom a Termék hozzáadása gombot, ez a gond megszűnik, de egy átlag felhasználót megzavarhat esetleg.

Ez a probléma nem a legnagyobb probléma, lehet wontfix.

**Comment by rolandandai** [comment]
Csak productionben jött elő a hiba, és a redis hozzáadásával megoldódott.
