### ISSUE TITLE
https://kbpr.sch.bme.hu/orders frontend crash

### ISSUE THREAD

**Issue by Bende126** [kir-dev/kbpr-web#49]
# Description
Ma hajnalban feltöltöttek egy 500 oldalas pdf-et, ami valószínűleg beakadt és vagy a "preview"-et vagy az odlalak száma az árat elcrasheli
![image](https://github.com/kir-dev/kbpr-web/assets/28264530/5fc1ec9b-fea3-4efb-a590-3a2b57226f9c)

# Steps to reproduce
 - 500 oldalas pdf feltöltése

# Egyéb
A rendelés leadás működik, bejelentkezni tudok, szerkesztési jogaim vannak és működnek, tehát szerintem csak frontendnél lesz probléma. Saját rendeléseimet látom

**Comment by SepsiLaszlo** [comment]
Fixed in this commit:
https://github.com/kir-dev/kbpr-web/commit/72d274ed991148d74545b8571207194d127ce617
